---
title: "rna-protein manuscript"
author: "Sienna Blanche"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    toc: yes
    toc_depth: 4
    toc_float: true
    number_sections: no
    df_print: paged
    code_folding: hide
    highlight: pygments
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=T, error=FALSE, message=FALSE, warning=FALSE}

if (!require("dplyr")) {install.packages("dplyr"); require("dplyr")}
if (!require("here")) {install.packages("here"); require("here")}
if (!require("viridis")) {install.packages("viridis"); require("viridis")}
if (!require("ggplot2")) {install.packages("ggplot2"); require("ggplot2")}
if (!require("ggrepel")) {install.packages("ggrepel"); require("ggrepel")}
if (!require("tidyr")) {install.packages("tidyr"); require("tidyr")}

here()
```

# Load Data

```{r, echo=T, error=FALSE, message=FALSE, warning=FALSE}

#Load the RPC dataset
RPC <- readRDS(here("Dataset", "RNA-Protein.rds"))

# load FCG dataset
FCG <- readRDS(here("Dataset", "FCG.RDS"))

```

# RNA-Protein Correlation (RPC) 

## RPC Heatmaps

### version 1

```{r, echo=T, error=FALSE, message=FALSE, warning=FALSE}

#with facets
ggplot(RPC %>% filter(Metric != "Transformed"), aes(x = Metric, y = Gene, fill = sum_delta)) +
  geom_tile() +
  scale_fill_viridis(option = "magma") +
  scale_y_discrete(limits = rev) +  
  facet_wrap(~ Metric, scales = "free_x", ncol = 3) +  # Line up metrics horizontally
  theme_minimal() +
  theme(
    axis.text.x = element_blank(),    # Remove x-axis text
    axis.ticks.x = element_blank(),   # Remove x-axis ticks
    strip.text = element_text(size = 12, angle = 0),  # Adjust facet label size and angle  
    panel.spacing = unit(1, "lines") # Space between facets
  ) +
  labs(
    title = "Sum of |Delta| Heat Maps",
    x = "",  # Remove x-axis label  
    y = "Target",
    fill = "|Delta|"
  )
```

### version 2

```{r, echo=T, error=FALSE, message=FALSE, warning=FALSE}

# Define  metrics list
metrics <- c("WT vs KO", "WT vs WT+A", "KO vs KO+A")   

# Loop for hm
for (i in metrics) {
  RPC_subset <- RPC %>%
    filter(Metric == i) %>%
    mutate(Gene = factor(Gene, levels = rev(unique(Gene))))
  
  p1 <- ggplot(RPC_subset, aes(x = Metric, y = Gene, fill = sum_delta)) +
    geom_tile() +
    geom_segment(  # Add  horizontal lines on the left
      aes(x = 0.4, xend = 0.5, y = as.numeric(Gene), yend = as.numeric(Gene)),
      color = "gray",
      linewidth = 0.3,
      inherit.aes = FALSE
    ) +
    scale_fill_viridis(
      option = "magma", 
      limits = c(0, 1.1),
      breaks = c(0, 0.50, 1)
      ) +
    theme_minimal() +
    theme(
      axis.text.x = element_blank(),    
      axis.ticks.x = element_blank(),   
      panel.grid.major.y = element_blank(),  
      strip.text = element_text(size = 12, angle = 0),  
      panel.spacing = unit(1, "lines")
    ) +
    labs(
      title = paste("Heat Map of |Delta| :", i),
      x = "",  
      y = "Target",
      fill = "|Delta|"
    )
  
  print(p1)
}
```

### version 3

```{r, echo=T, error=FALSE, message=FALSE, warning=FALSE}

# Loop for hm
for (i in metrics) {
  RPC_subset <- RPC %>%
    filter(Metric == i) %>%
    mutate(Gene = factor(Gene, levels = rev(unique(Gene))))

  p1 <- ggplot(RPC_subset, aes(x = Metric, y = Gene, fill = sum_delta)) +
    geom_tile(width = 0.1, height = 1) +
    geom_segment(
      aes(x = 0.4, xend = 0.5, y = as.numeric(Gene), yend = as.numeric(Gene)),
      inherit.aes = FALSE,
      color = "gray",
      linewidth = 0.5
    ) +
    scale_fill_viridis(
      option = "magma", 
      limits = c(0, 1.1), 
      breaks = c(0, 0.5, 1)
      ) +
    theme_minimal(base_size = 14) +
    theme(
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.text.y = element_text(size = 14, face = "bold"),
      axis.title.y = element_text(size = 16, face = "bold", margin = margin(r = 5)),
      plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
      legend.title = element_text(size = 14, face = "bold"),
      legend.text = element_text(size = 12),
      panel.grid.major = element_blank()
    ) +
    labs(
      title = paste("Heat Map of |Delta|:", i),
      x = "",
      y = "Target",
      fill = "|Delta|"
    )
  
  print(p1)
}
```

## Assessing Correlation

### WT/KO vs VEH/ANGII

#### Correlation Coeffiecent 

```{r echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, fig.width= 15, fig.height = 8, fig.align = 'center'}

# filter dfs
filtered_WT_VEH <- RPC %>% 
  filter(Metric %in% c("WT vs WT+A", "WT vs KO"))%>%
  select(Gene, Metric, sum_delta) %>%  # keep only relevant columns
  pivot_wider(names_from = Metric, values_from = sum_delta)

## spearman
cor_result_spearman_WT_VEH <- cor.test(filtered_WT_VEH$`WT vs KO`, filtered_WT_VEH$`WT vs WT+A`, method = "spearman")

corr_coeff_spearman_WT_VEH <- cor_result_spearman_WT_VEH$estimate
corr_pvalue_spearman_WT_VEH <- cor_result_spearman_WT_VEH$p.value

## pearson
cor_result_pearson_WT_VEH <- cor.test(filtered_WT_VEH$`WT vs KO`, filtered_WT_VEH$`WT vs WT+A`, method = "pearson")

corr_coeff_pearson_WT_VEH <- cor_result_pearson_WT_VEH$estimate
corr_pvalue_pearson_WT_VEH <- cor_result_pearson_WT_VEH$p.value
```

#### Visualizing Correlation 

```{r echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, fig.width= 15, fig.height = 8, fig.align = 'center'}

# spearman plot
ggplot(filtered_WT_VEH,aes(x = `WT vs KO`, y = `WT vs WT+A`)) +
  geom_point() +
  theme_classic() +
  theme(axis.line = element_line(size = 2, colour = "black"),
        text = element_text(size=20)) +
  labs(
    x = "Δ WT vs KO",
    y = "Δ VEH vs ANGII",
    title = "Spearman's Correlation between the change in WT v KO and VEH v ANGII"
  ) +
  annotate("text", 
           x = max(filtered_WT_VEH$`WT vs KO`, na.rm = TRUE), 
           y = min(filtered_WT_VEH$`WT vs WT+A`, na.rm = TRUE),
           label = paste("Correlation coefficient =", round(corr_coeff_spearman_WT_VEH, 2), "\n", "p-value =", round(corr_pvalue_spearman_WT_VEH, 2)),
           hjust = 1, vjust = -8, size = 6
           ) +
    geom_text_repel(aes(label = Gene), vjust = -0.5, size = 5) 

# pearson plot
ggplot(filtered_WT_VEH,aes(x = `WT vs KO`, y = `WT vs WT+A`)) +
  geom_point() +
  theme_classic() +
  theme(axis.line = element_line(size = 2, colour = "black"),
        text = element_text(size=20)) +
  labs(
    x = "Δ WT vs KO",
    y = "Δ VEH vs ANGII",
    title = "Pearson's Correlation between the change in WT v KO and VEH v ANGII"
  ) +
  annotate("text", 
           x = max(filtered_WT_VEH$`WT vs KO`, na.rm = TRUE), 
           y = min(filtered_WT_VEH$`WT vs WT+A`, na.rm = TRUE),
           label = paste("Correlation coefficient =", round(corr_coeff_pearson_WT_VEH, 2), "\n", "p-value =", round(corr_pvalue_pearson_WT_VEH, 2)),
           hjust = 1, vjust = -8, size = 6
           ) +
    geom_text_repel(aes(label = Gene), vjust = -0.5, size = 5) 
```

# RPC +FCG

## Merge dataframes

```{r, echo=T, error=FALSE, message=FALSE, warning=FALSE}

merged_df <- full_join(RPC, FCG, by = "Gene")
```

## Assessing Correlation

### WT/KO vs M/F

#### Correlation Coeffiecent 

```{r echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, fig.width= 15, fig.height = 8, fig.align = 'center'}

# filter dfs
filtered_WT_M <- merged_df %>% 
  filter(Metric.y == "MXY vs FXX", Metric.x == "WT vs KO")

## spearman
cor_result_spearman_WT_M <- cor.test(filtered_WT_M$abs_diff_ko, filtered_WT_M$`Sum Deltas`, method = "spearman")

corr_coeff_spearman_WT_M <- cor_result_spearman_WT_M$estimate
corr_pvalue_spearman_WT_M <- cor_result_spearman_WT_M$p.value

## pearson
cor_result_pearson_WT_M <- cor.test(filtered_WT_M$abs_diff_ko, filtered_WT_M$`Sum Deltas`, method = "pearson")

corr_coeff_pearson_WT_M <- cor_result_pearson_WT_M$estimate
corr_pvalue_pearson_WT_M <- cor_result_pearson_WT_M$p.value
```

#### Visualizing Correlation 

```{r echo=TRUE, error=FALSE, message=FALSE, warning=FALSE, fig.width= 15, fig.height = 8, fig.align = 'center'}

# spearman plot
ggplot(filtered_WT_M,aes(x = abs_diff_ko, y = `Sum Deltas`)) +
  geom_point() +
  theme_classic() +
  theme(axis.line = element_line(size = 2, colour = "black"),
        text = element_text(size=20)) +
  labs(
    x = "Δ WT vs KO",
    y = "Δ M vs F",
    title = "Spearman's Correlation between the change in WT v KO and M v F"
  ) +
  annotate("text", 
           x = max(filtered_WT_M$abs_diff_ko, na.rm = TRUE), 
           y = min(filtered_WT_M$`Sum Deltas`, na.rm = TRUE),
           label = paste("Correlation coefficient =", round(corr_coeff_spearman_WT_M, 2), "\n", "p-value =", round(corr_pvalue_spearman_WT_M, 2)),
           hjust = 1, vjust = -8, size = 6
           ) +
    geom_text_repel(aes(label = Gene), vjust = -0.5, size = 5) 

# pearson plot
ggplot(filtered_WT_M,aes(x = abs_diff_ko, y = `Sum Deltas`)) +
  geom_point() +
  theme_classic() +
  theme(axis.line = element_line(size = 2, colour = "black"),
        text = element_text(size=20)) +
  labs(
    x = "Δ WT vs KO",
    y = "Δ M vs F",
    title = "Pearson's Correlation between the change in WT v KO and M v F"
  ) +
  annotate("text", 
           x = max(filtered_WT_M$abs_diff_ko, na.rm = TRUE), 
           y = min(filtered_WT_M$`Sum Deltas`, na.rm = TRUE),
           label = paste("Correlation coefficient =", round(corr_coeff_pearson_WT_M, 2), "\n", "p-value =", round(corr_pvalue_pearson_WT_M, 2)),
           hjust = 1, vjust = -8, size = 6
           ) +
    geom_text_repel(aes(label = Gene), vjust = -0.5, size = 5) 
```


